#
# Copyright (C) 2020 diva.exchange
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Author/Maintainer: Konrad Bächler <konrad@diva.exchange>
#

version: "3.7"
services:
  n1.db.testnet.ustb.edu:
    container_name: n1.db.testnet.ustb.edu
    image: postgres:10-alpine
    command: -c max_prepared_transactions=100
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: iroha
      POSTGRES_USER: iroha
      POSTGRES_PASSWORD: iroha
    volumes:
      - n1.db.testnet.ustb.edu:/var/lib/postgresql/data/
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.21

  n1.testnet.ustb.edu:
    container_name: n1.testnet.ustb.edu
    image: maning00/iroha:dev
    restart: unless-stopped
    stop_grace_period: 5s
    environment:
      IP_POSTGRES: 172.29.101.21
      NAME_DATABASE: iroha
      NAME_PEER: n1
      BLOCKCHAIN_NETWORK: testnet.ustb.edu
    volumes:
      - n1.testnet.ustb.edu:/opt/iroha
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.121
    extra_hosts:
      - n1.testnet.ustb.edu:172.29.101.121
      - n2.testnet.ustb.edu:172.29.101.122
      - n3.testnet.ustb.edu:172.29.101.123
      - n4.testnet.ustb.edu:172.29.101.124
      - n5.testnet.ustb.edu:172.29.101.125
      - n6.testnet.ustb.edu:172.29.101.126
      - n7.testnet.ustb.edu:172.29.101.127

  n2.db.testnet.ustb.edu:
    container_name: n2.db.testnet.ustb.edu
    image: postgres:10-alpine
    command: -c max_prepared_transactions=100
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: iroha
      POSTGRES_USER: iroha
      POSTGRES_PASSWORD: iroha
    volumes:
      - n2.db.testnet.ustb.edu:/var/lib/postgresql/data/
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.22

  n2.testnet.ustb.edu:
    container_name: n2.testnet.ustb.edu
    image: maning00/iroha:dev
    restart: unless-stopped
    stop_grace_period: 5s
    environment:
      IP_POSTGRES: 172.29.101.22
      NAME_DATABASE: iroha
      NAME_PEER: n2
      BLOCKCHAIN_NETWORK: testnet.ustb.edu
    volumes:
      - n2.testnet.ustb.edu:/opt/iroha
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.122
    extra_hosts:
      - n1.testnet.ustb.edu:172.29.101.121
      - n2.testnet.ustb.edu:172.29.101.122
      - n3.testnet.ustb.edu:172.29.101.123
      - n4.testnet.ustb.edu:172.29.101.124
      - n5.testnet.ustb.edu:172.29.101.125
      - n6.testnet.ustb.edu:172.29.101.126
      - n7.testnet.ustb.edu:172.29.101.127

  n3.db.testnet.ustb.edu:
    container_name: n3.db.testnet.ustb.edu
    image: postgres:10-alpine
    command: -c max_prepared_transactions=100
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: iroha
      POSTGRES_USER: iroha
      POSTGRES_PASSWORD: iroha
    volumes:
      - n3.db.testnet.ustb.edu:/var/lib/postgresql/data/
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.23

  n3.testnet.ustb.edu:
    container_name: n3.testnet.ustb.edu
    image: maning00/iroha:dev
    restart: unless-stopped
    stop_grace_period: 5s
    environment:
      IP_POSTGRES: 172.29.101.23
      NAME_DATABASE: iroha
      NAME_PEER: n3
      BLOCKCHAIN_NETWORK: testnet.ustb.edu
    volumes:
      - n3.testnet.ustb.edu:/opt/iroha
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.123
    extra_hosts:
      - n1.testnet.ustb.edu:172.29.101.121
      - n2.testnet.ustb.edu:172.29.101.122
      - n3.testnet.ustb.edu:172.29.101.123
      - n4.testnet.ustb.edu:172.29.101.124
      - n5.testnet.ustb.edu:172.29.101.125
      - n6.testnet.ustb.edu:172.29.101.126
      - n7.testnet.ustb.edu:172.29.101.127

  n4.db.testnet.ustb.edu:
    container_name: n4.db.testnet.ustb.edu
    image: postgres:10-alpine
    command: -c max_prepared_transactions=100
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: iroha
      POSTGRES_USER: iroha
      POSTGRES_PASSWORD: iroha
    volumes:
      - n4.db.testnet.ustb.edu:/var/lib/postgresql/data/
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.24

  n4.testnet.ustb.edu:
    container_name: n4.testnet.ustb.edu
    image: maning00/iroha:dev
    restart: unless-stopped
    stop_grace_period: 5s
    environment:
      IP_POSTGRES: 172.29.101.24
      NAME_DATABASE: iroha
      NAME_PEER: n4
      BLOCKCHAIN_NETWORK: testnet.ustb.edu
    volumes:
      - n4.testnet.ustb.edu:/opt/iroha
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.124
    extra_hosts:
      - n1.testnet.ustb.edu:172.29.101.121
      - n2.testnet.ustb.edu:172.29.101.122
      - n3.testnet.ustb.edu:172.29.101.123
      - n4.testnet.ustb.edu:172.29.101.124
      - n5.testnet.ustb.edu:172.29.101.125
      - n6.testnet.ustb.edu:172.29.101.126
      - n7.testnet.ustb.edu:172.29.101.127

  n5.db.testnet.ustb.edu:
    container_name: n5.db.testnet.ustb.edu
    image: postgres:10-alpine
    command: -c max_prepared_transactions=100
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: iroha
      POSTGRES_USER: iroha
      POSTGRES_PASSWORD: iroha
    volumes:
      - n5.db.testnet.ustb.edu:/var/lib/postgresql/data/
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.25

  n5.testnet.ustb.edu:
    container_name: n5.testnet.ustb.edu
    image: maning00/iroha:dev
    restart: unless-stopped
    stop_grace_period: 5s
    environment:
      IP_POSTGRES: 172.29.101.25
      NAME_DATABASE: iroha
      NAME_PEER: n5
      BLOCKCHAIN_NETWORK: testnet.ustb.edu
    volumes:
      - n4.testnet.ustb.edu:/opt/iroha
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.125
    extra_hosts:
      - n1.testnet.ustb.edu:172.29.101.121
      - n2.testnet.ustb.edu:172.29.101.122
      - n3.testnet.ustb.edu:172.29.101.123
      - n4.testnet.ustb.edu:172.29.101.124
      - n5.testnet.ustb.edu:172.29.101.125
      - n6.testnet.ustb.edu:172.29.101.126
      - n7.testnet.ustb.edu:172.29.101.127

  n6.db.testnet.ustb.edu:
    container_name: n6.db.testnet.ustb.edu
    image: postgres:10-alpine
    command: -c max_prepared_transactions=100
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: iroha
      POSTGRES_USER: iroha
      POSTGRES_PASSWORD: iroha
    volumes:
      - n6.db.testnet.ustb.edu:/var/lib/postgresql/data/
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.26

  n6.testnet.ustb.edu:
    container_name: n6.testnet.ustb.edu
    image: maning00/iroha:dev
    restart: unless-stopped
    stop_grace_period: 5s
    environment:
      IP_POSTGRES: 172.29.101.26
      NAME_DATABASE: iroha
      NAME_PEER: n6
      BLOCKCHAIN_NETWORK: testnet.ustb.edu
    volumes:
      - n6.testnet.ustb.edu:/opt/iroha
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.126
    extra_hosts:
      - n1.testnet.ustb.edu:172.29.101.121
      - n2.testnet.ustb.edu:172.29.101.122
      - n3.testnet.ustb.edu:172.29.101.123
      - n4.testnet.ustb.edu:172.29.101.124
      - n5.testnet.ustb.edu:172.29.101.125
      - n6.testnet.ustb.edu:172.29.101.126
      - n7.testnet.ustb.edu:172.29.101.127

  n7.db.testnet.ustb.edu:
    container_name: n7.db.testnet.ustb.edu
    image: postgres:10-alpine
    command: -c max_prepared_transactions=100
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: iroha
      POSTGRES_USER: iroha
      POSTGRES_PASSWORD: iroha
    volumes:
      - n7.db.testnet.ustb.edu:/var/lib/postgresql/data/
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.27

  n7.testnet.ustb.edu:
    container_name: n7.testnet.ustb.edu
    image: maning00/iroha:dev
    restart: unless-stopped
    stop_grace_period: 5s
    environment:
      IP_POSTGRES: 172.29.101.27
      NAME_DATABASE: iroha
      NAME_PEER: n7
      BLOCKCHAIN_NETWORK: testnet.ustb.edu
    volumes:
      - n7.testnet.ustb.edu:/opt/iroha
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.127
    extra_hosts:
      - n1.testnet.ustb.edu:172.29.101.121
      - n2.testnet.ustb.edu:172.29.101.122
      - n3.testnet.ustb.edu:172.29.101.123
      - n4.testnet.ustb.edu:172.29.101.124
      - n5.testnet.ustb.edu:172.29.101.125
      - n6.testnet.ustb.edu:172.29.101.126
      - n7.testnet.ustb.edu:172.29.101.127

  explorer.testnet.ustb.edu:
    container_name: explorer.testnet.ustb.edu
    image: divax/iroha-explorer:latest
    restart: unless-stopped
    environment:
      IP_EXPLORER: 0.0.0.0
      PORT_EXPLORER: 3920
      PATH_IROHA: /tmp/iroha/
    volumes:
      - n1.testnet.ustb.edu:/tmp/iroha/:ro
    networks:
      network.testnet.ustb.edu:
        ipv4_address: 172.29.101.3

networks:
  network.testnet.ustb.edu:
    internal: true
    name: network.testnet.ustb.edu
    ipam:
      driver: default
      config:
        - subnet: 172.29.101.0/24

volumes:
  n1.db.testnet.ustb.edu:
    name: n1.db.testnet.ustb.edu
  n2.db.testnet.ustb.edu:
    name: n2.db.testnet.ustb.edu
  n3.db.testnet.ustb.edu:
    name: n3.db.testnet.ustb.edu
  n4.db.testnet.ustb.edu:
    name: n4.db.testnet.ustb.edu
  n5.db.testnet.ustb.edu:
    name: n5.db.testnet.ustb.edu
  n6.db.testnet.ustb.edu:
    name: n6.db.testnet.ustb.edu
  n7.db.testnet.ustb.edu:
    name: n7.db.testnet.ustb.edu
  n1.testnet.ustb.edu:
    name: n1.testnet.ustb.edu
  n2.testnet.ustb.edu:
    name: n2.testnet.ustb.edu
  n3.testnet.ustb.edu:
    name: n3.testnet.ustb.edu
  n4.testnet.ustb.edu:
    name: n4.testnet.ustb.edu
  n5.testnet.ustb.edu:
    name: n5.testnet.ustb.edu
  n6.testnet.ustb.edu:
    name: n6.testnet.ustb.edu
  n7.testnet.ustb.edu:
    name: n7.testnet.ustb.edu

