#
# Copyright (C) 2020 diva.exchange
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Author/Maintainer: Konrad Bächler <konrad@diva.exchange>
#

FROM ubuntu:latest

LABEL author="Konrad Baechler <konrad@diva.exchange>" \
  maintainer="Konrad Baechler <konrad@diva.exchange>" \
  name="diva-iroha" \
  description="Distributed digital value exchange upholding security, reliability and privacy" \
  url="https://diva.exchange"

ENV TZ=Europe/Zurich
ARG DEBIAN_FRONTEND=nointeractive

COPY entrypoint-build.sh /

RUN apt-get update \
  && apt-get -y --no-install-recommends install \
    build-essential \
    ninja-build \
    pkg-config \
    git \
    ca-certificates \
    tar \
    curl \
    zip \
    unzip \
    cmake \
  && curl -LO https://golang.org/dl/go1.15.6.linux-amd64.tar.gz \
  && tar -C /usr/local -xzf go1.15.6.linux-amd64.tar.gz \
  && export PATH=$PATH:/usr/local/go/bin \
  && go get -u github.com/golang/protobuf/protoc-gen-go \
  && cp /root/go/bin/protoc-gen-go /usr/local/bin/ \
  && chmod +x /entrypoint-build.sh

VOLUME [ "/root/" ]
WORKDIR /root/
ENTRYPOINT ["/entrypoint-build.sh"]
